<a href="https://colab.research.google.com/github/TaylorL74/data-and-python/blob/main/Copy_of_D_05a_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Introduction to Numpy

---


## Creating new Numpy Arrays

As shown in the presentation, it is convention to import the whole numpy library using an alias:

`import numpy as np`

Every time you want to use a function from the numpy library you use the syntax:  

`np.function_name()`  

Create a new numpy array from a Python list of numbers
   
`arr = np.array([1,2,3])`

Or a new numpy matrix from a Python 2 dimensional list of numbers

`matrix = np.array([[1,2,3],[4,5,6]])`

Create a numpy array from a dataframe column (series):

`arr = df['column name'].to_numpy(datatype)`

where the datatype matches the data type of the column.



### Exercise 1 - create a new numpy array to hold the numbers from 1 to 10
---

Write a function called `make_array()` which will:
*   create a list of the numbers 1 to 10     -   *hint: try using range() if you are more confident working with lists*
*   create a new numpy array called **new_array** from that list
*   print `new_array`

Expected output:  
`[1 2 3 4 5 6 7 8 9 10] `



In [ ]:
import numpy as np

def make_array():
  # Creating an empty list and setting a number to 1 for use in the loop
  number_list = []
  number = 1
  # Creating a loop that will add the numbers 1 through 10 to the empty list
  for i in range(10):
    number_list.append(number)
    number = number + 1

  # Turning list into an array and printing it
  new_array = np.array(number_list)
  print(new_array)

make_array()

[ 1  2  3  4  5  6  7  8  9 10]


## Setting the number type in memory

As a reminder, set the memory type as follows, where **int8** is the datetype you wish to use.

`new_array = np.array([1, 2, 3], np.int8)`    


---
### Exercise 2 - create list of smallish numbers

Write a function which will:
*   assign the list `[31112, 32321, 24567, 456, 324, 789]` to a variable called **num_list** (which has been done for you already)   
*   create a new numpy array called **new_array** from `num_list`, with data size `int16`
*   print `new_array`  


Expected output:   
```
[31112 32321 24567 456 324 789]
```

*As an extra challenge, if you've complete the worksheet on user defined functions, change the function to accept num_list as a parameter, then the function should return the numpy array rather than print it.*

In [ ]:
import numpy as np

def create_new_array(num_list):

  new_array = np.array([num_list], np.int16)
  print(new_array)
  return new_array



num_list = [31112, 32321, 24567, 456, 324, 789]
create_new_array(num_list)


[[31112 32321 24567   456   324   789]]


array([[31112, 32321, 24567,   456,   324,   789]], dtype=int16)

---
### Exercise 3 - create a numpy array from a pandas dataframe column

Write a function which  will create a numpy array from the Fare column of the titanic dataset.

*Recap*:  *the Fare column is df['Fare'] (assuming your dataframe is called df)*

*  create a dataframe from the data set in the file at this url:  https://raw.githubusercontent.com/pandas-dev/pandas/master/doc/data/titanic.csv (this has been done for you)
*  create a new numpy array called **fare** from the `Fare` column (*remember to specify the data type e.g. np.int32, float64 when using* `df.to_numpy()` *and consider what the datatype might be from looking at the expected output below*)  
*  print the `fare` array

Expected output:  
```
array([  7.25  ,  71.2833,   7.925 , ......  23.45  ,  30.    ,   7.75  ])
```

  

In [ ]:
import pandas as pd
import numpy as np

url = "https://raw.githubusercontent.com/pandas-dev/pandas/master/doc/data/titanic.csv"
df = pd.read_csv(url)

def create_fare_series():
  fare_array = np.array(df["Fare"], np.float64)
  print(fare_array)



create_fare_series()

[  7.25    71.2833   7.925   53.1      8.05     8.4583  51.8625  21.075
  11.1333  30.0708  16.7     26.55     8.05    31.275    7.8542  16.
  29.125   13.      18.       7.225   26.      13.       8.0292  35.5
  21.075   31.3875   7.225  263.       7.8792   7.8958  27.7208 146.5208
   7.75    10.5     82.1708  52.       7.2292   8.05    18.      11.2417
   9.475   21.       7.8958  41.5792   7.8792   8.05    15.5      7.75
  21.6792  17.8     39.6875   7.8     76.7292  26.      61.9792  35.5
  10.5      7.2292  27.75    46.9      7.2292  80.      83.475   27.9
  27.7208  15.2458  10.5      8.1583   7.925    8.6625  10.5     46.9
  73.5     14.4542  56.4958   7.65     7.8958   8.05    29.      12.475
   9.       9.5      7.7875  47.1     10.5     15.85    34.375    8.05
 263.       8.05     8.05     7.8542  61.175   20.575    7.25     8.05
  34.6542  63.3583  23.      26.       7.8958   7.8958  77.2875   8.6542
   7.925    7.8958   7.65     7.775    7.8958  24.15    52.      14.4542
  

---
### Exercise 4 - print first 5 and last 5 items in numpy array

Write a function which will create the same array as in the previous exercise (created from the Fare column in the titanic dataset):

*  print the first 5 items in the array (one per line)
*  print 5 lines of three dots (ie ...)
*  print the last 5 items in the array (one per line)

*Hint: You can slice an array from the beggining or the end and then print the values from that slice.*

Note: If you have run the cell above in this session, the dataframe **df** will still be available for you to use.

**Expected output**:  
7.25 <br>
71.2833 <br>
7.925 <br>
53.1 <br>
8.05  
...  
...  
...  
...  
...  
13.0 <br>
30.0 <br>
23.45 <br>
30.0 <br>
7.75



In [ ]:
import pandas as pd
import numpy as np

url = "https://raw.githubusercontent.com/pandas-dev/pandas/master/doc/data/titanic.csv"
df = pd.read_csv(url)

def show_head_tail():
  # Creating an array from the fare column in the table
  fare_array = np.array(df["Fare"], np.float64)

  # Using indexing to print the first 5 numbers in the array
  for head_number in range(5):
    print(fare_array[head_number])

  # Printing elipses to indicate a gap in the data
  for i in range(3):
    print("...")

  # Using indexing to print the last 5 items in the array
  tail_number = -5
  for number in range(5):
    print(fare_array[tail_number])
    tail_number += 1


show_head_tail()

7.25
71.2833
7.925
53.1
8.05
...
...
...
13.0
30.0
23.45
30.0
7.75


---
### Exercise 5 - increase whole array by 20

Write a function which will:
*  create a numpy array of 12 numbers
*  create a new array adding 20 to each of the items in the first array  
*  print the new array

Test input:  
`[1,2,3,4,5,6,7,8,1,2,3,4]`

Expected output:  
`[21 22 23 24 25 26 27 28 21 22 23 24]`

In [ ]:
import numpy as np

def increase_array():
  number_array = np.array([1,2,3,4,5,6,7,8,1,2,3,4], np.int16)
  new_array = number_array + 20
  print(new_array)

increase_array()

[21 22 23 24 25 26 27 28 21 22 23 24]



---
### Exercise 6 - convert Titanic fares into 21st century values

Write a function which will:    
*  create a numpy array from the Fare column of the Titanic dataframe `df`
*  convert the fares into current value (multiply by a factor of 120.7045 - source https://www.in2013dollars.com/uk/inflation/1912?amount=32 *accessed 22/1/2022*)
*  sort the converted fares
*  print the first (the smallest) and last (greatest) values of the sorted fares.

Expected output:  
```
0.0
61840.4399214

```




In [ ]:
import pandas as pd
import numpy as np

url = "https://raw.githubusercontent.com/pandas-dev/pandas/master/doc/data/titanic.csv"
df = pd.read_csv(url)

def get_current_fares():
  # Creating the fares array and multiplying it to change the values to modern equivalent
  fare_array = np.array(df["Fare"], np.float64)
  modern_fares = fare_array * 120.7045
  # Sorting the array from smallest to largest and printing the smallest and largest values
  modern_fares.sort()
  print(modern_fares[0])
  print(modern_fares[-1])


get_current_fares()

0.0
61840.4399214


### Exercise 7 - filtering an array

Write a function that will take a numpy array of 20 random numbers between 1 and 10 use array filtering to print the following:
* numbers equal to 5 (arr == 5)
* numbers less than or equal to 5 (arr <= 5)
* numbers greater than 5 (arr > 5)
* numbers not equal to 5 (arr != 5)

Expected output:

`[5 5]` <br>
`[4 5 2 1 3 1 2 4 5 3 3 1]` <br>
`[9 8 8 7 6 7 8 9]` <br>
`[4 2 9 1 8 3 1 8 2 7 4 3 6 7 3 1 8 9]`


In [ ]:
def filter_an_array():
  arr = np.array([4, 5, 2, 9, 1, 8, 3, 1, 8, 2, 7, 4, 5, 3, 6, 7, 3, 1, 8, 9])

  # Creating the filter conditions, applying the filter, and printing the array of filtered results. Repeat for each condition
  filter_equal_five = arr == 5
  passed_equal_five = arr[filter_equal_five]
  print(passed_equal_five)

  filter_less_five = arr <= 5
  passed_less_five = arr[filter_less_five]
  print(passed_less_five)

  filter_greater_five = arr > 5
  passed_greater_five = arr[filter_greater_five]
  print(passed_greater_five)

  filter_not_five = arr != 5
  passed_not_five = arr[filter_not_five]
  print(passed_not_five)

filter_an_array()

[5 5]
[4 5 2 1 3 1 2 4 5 3 3 1]
[9 8 8 7 6 7 8 9]
[4 2 9 1 8 3 1 8 2 7 4 3 6 7 3 1 8 9]


### Exercise 8 - How many survivors?

The `Survived` column in the titanic dataset contains two possible values: 0 if the person did not survive and 1 if they did.

Write a function that will:

* create a numpy array from the Survived column of the titanic dataframe `df`
* count the length of the array (*Hint: you can use the `len()` function in the same way as you have done for strings and lists*) to find out how many people were on the titanic
* filter the array for values greater than 0
* find the length of the filtered array and calculate the percentage of survivors, rounded to 1 decimal place
* print a statement that says how many people were on the titanic and what percentage survived.

In [ ]:
import pandas as pd
import numpy as np

url = "https://raw.githubusercontent.com/pandas-dev/pandas/master/doc/data/titanic.csv"
df = pd.read_csv(url)

def get_survival_rate():
  # Creating an array of all the passengers and their survived status, and using that to find the total count of passengers
  passenger = np.array(df["Survived"], np.int64)
  passenger_length = len(passenger)

  # Using filtering to find how many passengers survived
  filter_survivors = passenger > 0
  passed = passenger[filter_survivors]

  survivors = len(passed)

  # Calculating the percentage of survivors
  percentage = (survivors / passenger_length) * 100

  print(f"There were {passenger_length} people on the Titanic. Only {round(percentage, 1)}% of people survived.")


get_survival_rate()

There were 891 people on the Titanic. Only 38.4% of people survived.


### Exercise 9 - Passenger Classes

The `Pclass` column of the titanic dataset `df` shows the class of each passenger aboard, numbered 1 for first class, 2 for second class and 3 for third.

Write a function that will
* create a numpy array from the `Pclass` column
* filters the array for only 1st class passengers and stores the result in a new variable
* prints the number of first class passengers
* repeats steps two and three for second and third class passengers

Expected output:

There were 216 first class passengers <br>
There were 184 second class passengers <br>
There were 491 third class passengers

In [18]:
import pandas as pd
import numpy as np

url = "https://raw.githubusercontent.com/pandas-dev/pandas/master/doc/data/titanic.csv"
df = pd.read_csv(url)

def get_class_counts():
  class_array = np.array(df["Pclass"], np.int64)

  # Creating a filter for first class, applying it to the array and calculating the length of the array to find the number of first class passengers. Repeat for each class.
  filter_first_class = class_array == 1
  passed_first = len(class_array[filter_first_class])
  print(f"There were {passed_first} people aboard Titanic's first class.")

  filter_second_class = class_array == 2
  passed_second = len(class_array[filter_second_class])
  print(f"There were {passed_second} people aboard Titanic's second class.")

  filter_third_class = class_array == 3
  passed_third = len(class_array[filter_third_class])
  print(f"There were {passed_third} people aboard Titanic's third class.")
  # Passing the passenger count of each class out of the function for use in the next exercise
  return passed_first, passed_second, passed_third


first_class_count, second_class_count, third_class_count = get_class_counts()

There were 216 people aboard Titanic's first class.
There were 184 people aboard Titanic's second class.
There were 491 people aboard Titanic's third class.


### Exercise 10 - Survivor Stats

When we have arrays that represent different columns of the same dataset, we can create a boolean mask from one array and then apply it as a filter to a different array.

Write a function that does the following:
* creates separate numpy arrays of the `Pclass` and `Survived` columns of the titanic dataset
* creates a boolean mask to filter those that died (value == 0) using the Survived array
* apply the filter to the Pclass array, assigning it to a new variable
* use filtering in the same way as the previous exercise to find out how many people in each class were aboard the titanic and how many survived
* calculate the percentage of people in each class who survived. Do the results surpise you?

As an extra challenge, if you have completed the worksheet on user-defined functions and are confident with re-using functions, change the `get_class_counts()` function to return a value and use this in your `get_survivor_class_stats()` function.

In [22]:
import numpy as np
import pandas as pd

url = "https://raw.githubusercontent.com/pandas-dev/pandas/master/doc/data/titanic.csv"
df = pd.read_csv(url)

# Passing data from the last exercise about the number of passegers in each class
def get_survivor_class_stats(first_class_count, second_class_count, third_class_count):
  class_array = np.array(df["Pclass"], np.int64)
  survivors_array = np.array(df["Survived"], np.int64)

  # Creating a filter for the survivors using the Survivors array, and applying it to the class array to create a new array of the passengers that died and their class type
  filter_died = survivors_array == 0
  class_died = class_array[filter_died]

  # Filtering the new array by class to find the number of passengers that died in that class, repeat for each class
  filter_first_class_deaths = class_died == 1
  first_class_deaths = len(class_died[filter_first_class_deaths])

  # Calculating the percentage that died in the class, and from that the percentage of survivors, repeat for each class
  percentage_died_first = (first_class_deaths / first_class_count) * 100
  percentage_survived_first = 100 - percentage_died_first

  filter_second_class_deaths = class_died == 2
  second_class_deaths = len(class_died[filter_second_class_deaths])

  percentage_died_second = (second_class_deaths / second_class_count) * 100
  percentage_survived_second = 100 - percentage_died_second

  filter_third_class_deaths = class_died == 3
  third_class_deaths = len(class_died[filter_third_class_deaths])

  percentage_died_third = (third_class_deaths / third_class_count) * 100
  percentage_survived_third = 100 - percentage_died_third

  # Printing the percentage of survivors from each class and rounding the percentage to 0 decimal spaces
  print(f"{round(percentage_survived_first, 0)}% of people in First Class survived the sinking of the Titanic")
  print(f"{round(percentage_survived_second, 0)}% of people in Second Class survived the sinking of the Titanic")
  print(f"{round(percentage_survived_third, 0)}% of people in Third Class survived the sinking of the Titanic")

get_survivor_class_stats(first_class_count, second_class_count, third_class_count)

63.0% of people in First Class survived the sinking of the Titanic
47.0% of people in Second Class survived the sinking of the Titanic
24.0% of people in Third Class survived the sinking of the Titanic


# Reflection
----

## What skills have you demonstrated in completing this notebook?

Your answer: I have demonstrated that I understand how to import numpy and create arrays both from freestanding data, and data imported from files using pandas. I have shown that I know how to alter and perform calculations to all data in an array at once, and that I understand how to create filters and apply them to other arrays in order to analyse data from multiple columns and variables.

## What caused you the most difficulty?

Your answer: In exercise 4 I encountered errors due to unnecessary square brackets I had included when creating the array e.g.

fare_array = np.array([df["Fare"]], np.float64)

instead of

fare_array = np.array(df["Fare"], np.float64) )